### ISSUE TITLE
ImportError: cannot import name quick_pileup

### ISSUE THREAD

**Issue by varamhcu** [aawdeh/WACS#1]
I created a fresh conda environment installed python (v 2.7.9), then installed samtools, bedtools. I also installed numpy, scipy, pands through pip as mentioned in readme file. Then  I run the "python setup.py install" to install the provided macs2 algorithm. macs2 algorithm is successfully installed, the subcommand callpeak_wacs is observed. 

Now I performed peak calling with 'callpeak_wacs' sub command using the bam files (test and control) and respective control weights as input. Here I am attaching the code used to perform peak calling.

macs2 \
callpeak_wacs \
-t IP_B5_R1_sorted_unique.bam \
-c MOCK_B5_R1_sorted_unique.bam 20190125_A-MOCK_B6_R1_sorted_unique.bam \
-w 0.13866679257704465 0.42968144125181074 \
-g 3.73e+08 \
-f BAM \
-n B5 \
--outdir B5_Out 

This returned the following error. 

Traceback (most recent call last):
  File "/home/anaconda3/envs/py279_2/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.3', 'macs2')
  File "/home/anaconda3/envs/py279_2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/anaconda3/envs/py279_2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/home/anaconda3/envs/py279_2/lib/python2.7/site-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 754, in <module>
    main()
  File "/home/anaconda3/envs/py279_2/lib/python2.7/site-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 61, in main
    from MACS2.callpeakw_cmd import run
  File "/home/anaconda3/envs/py279_2/lib/python2.7/site-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/MACS2/callpeakw_cmd.py", line 34, in <module>
    from MACS2.OptValidator import opt_validate_wacs
  File "/home/anaconda3/envs/py279_2/lib/python2.7/site-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "MACS2/IO/Parser.pyx", line 27, in init MACS2.IO.Parser
  File "MACS2/IO/FixWidthTrack.pyx", line 31, in init MACS2.IO.FixWidthTrack
  File "MACS2/Pileup.pyx", line 23, in init MACS2.Pileup
  File "MACS2/IO/PairedEndTrack.pyx", line 25, in init MACS2.IO.PairedEndTrack
ImportError: cannot import name quick_pileup

Please let me know if I perform any mistakes in performing peak calling or installation errors.

**Comment by varamhcu** [comment]
I have redone the installation again. This time I performed the installation of macs2 provided in the downloaded folder by "python setup_w_cython.py install ". This lets me run the peak calling without any error. 

Thank you
